name: Update Age

on:
  schedule:
    - cron: "0 3 24 4 *"  # 24/04 às 00h00 (Brasília) = 03h00 UTC
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Increment age
        run: |
          AGE=$(grep -oE '<!--AGE-->[0-9]+<!--/AGE-->' README.md | grep -oE '[0-9]+')
          NEW_AGE=$((AGE + 1))
          sed -i "s/<!--AGE-->[0-9]\+<!--\/AGE-->/<!--AGE-->${NEW_AGE}<!--\/AGE-->/" README.md
      - name: Commit
        run: |
          git config user.name "GitHub-Actions[BOT]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automatico: Atualizada a idade no README" || exit 0
          git push